name: "FABrication Output"
on:
  push:
    paths:
      - 'PCB/**'
    tags:
      - pcb-v*
  workflow_dispatch:
    

jobs:
  FabricationOutputs:
    env:
      BaseFileName: megadesk
      Timezone: America/New_york
      OutputFolder: PCB/KiBotOutput
    runs-on: ubuntu-latest

    steps:
      # Check out the files
      - uses: actions/checkout@v3

      # Get the current date and time, in the timezone specified above, for use later.
      - name: Get current date and time
        id: date
        run: echo "date=$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d %T')" >> $GITHUB_OUTPUT
        
      # Get the current date
      - name: Get current date
        id: date_only
        run: echo "date_only=$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      # Actually run KiBot to generate all the files. The KiBot script used is
      # in the .kibot/release.kibot.yaml folder.
      - name: KiBot
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: PCB/.kibot/megadesk.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: PCB/megadesk.kicad_sch
          board: PCB/megadesk.kicad_pcb

      # Archive all the artifacts from output and attach to the action's results.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BaseFileName }}-fab-${{ steps.date_only.outputs.date_only }}
          path: ${{ env.OutputFolder }}/**

      # Conditional release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/pcb-v')
        with:
          files: |
            ${{ env.OutputFolder }}/*.zip
            ${{ env.OutputFolder }}/*.pdf
        