name: "PCB Fabrication"
on:
  push:
    paths:
      - 'pcb/**'
    tags:
      - pcb-v*
  workflow_dispatch:
    

jobs:
  FabricationOutputs:
    env:
      BaseFileName: ${{ github.event.repository.name }}
      Timezone: America/Toronto
      OutputFolder: PCB/KiBotOutput
    runs-on: ubuntu-latest

    steps:
      # Check out the files
      - uses: actions/checkout@v2

      # Get the current date and time, in the timezone specified above, for use later.
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d %T')"

      # Get the current date
      - name: Get current date
        id: date_only
        run: echo "::set-output name=date_only::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d')"

      # Actually run KiBot to generate all the files. The KiBot script used is
      # in the .kibot/release.kibot.yaml folder.
      - name: KiBot
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: pcb/.kibot/kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: pcb/${{ env.BaseFileName }}.kicad_sch
          board: pcb/${{ env.BaseFileName }}.kicad_pcb

      # Archive all the artifacts from output and attach to the action's results.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BaseFileName }}-fab-${{ steps.date_only.outputs.date_only }}
          path: ${{ env.OutputFolder }}/**

      # Conditional release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/pcb-v')
        with:
          files: |
            ${{ env.OutputFolder }}/*.zip
            ${{ env.OutputFolder }}/*.pdf
        