# This workflow generates Gerbers for reviewing before release. 
# The version number and date of the design is automatically updated on the PCB. 
# The version number is set via an environment variable
# and by default is `pre-release` since this runs outside of the release process
# so there's no formal release number to use.

# To use this workflow in your own repo you need to edit the environment variables in the env: section
# below.
name: "KiBot - Fabrication and Documentation (push)"

on: push


jobs:
  FabricationOutputs:
    env:
      BaseFileName: megadesk
      Timezone: America/New_york
      OutputFolder: PCB/KiBotOutput
    runs-on: ubuntu-latest

    # These are all the steps that generate the files.
    steps:
      # Check out the files
      - uses: actions/checkout@v2

      # Get the current date and time, in the timezone specified above, for use later.
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d %T')"

      # Get the current date
      - name: Get current date
        id: date_only
        run: echo "::set-output name=date_only::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d')"

      # Actually run KiBot to generate all the files. The KiBot script used is
      # in the .kibot/release.kibot.yaml folder.
      - name: KiBot
        uses: INTI-CMNB/KiBot@v1_k6
        with:
          config: PCB/.kibot/megadesk.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: PCB/megadesk.kicad_sch
          board: PCB/megadesk.kicad_pcb

      # Archive all the artifacts from output and attach to the action's results.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BaseFileName }}-${{ steps.date_only.outputs.date_only }}
          path: ${{ env.OutputFolder }}/**
